version: '3.4'
services:
  hal:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        version: "1.34.0"
    image: hal:1.0
    volumes: 
      - /Users/michalmarszalek/utils/hal/.hal:/home/spinnaker/.hal
      - /Users/michalmarszalek/utils/hal/utils/:/home/spinnaker/utils
    environment:
      - KUBECONFIG=/home/spinnaker/utils/.kube/config
      - GOOGLE_APPLICATION_CREDENTIALS=/home/spinnaker/secret.json
    ports:
      - "9000:9000"
      - "8084:8084"
    stdin_open: true
    tty: true